let express=require("express")
const { adduser, login, resetpwd,islogin,isadmin } = require("../controllers/usercont")
const { upload, add, getprod, upddct, deldct, updprod, updpimg, addrv, deleteProd } = require("../controllers/prodcont")
const { addcart, incqty, decqty, delcart, getcart } = require("../controllers/cartcont")
let route=new express.Router()
route.post("/adduser",adduser)
route.post("/login",login)
route.post("/addprod",upload.single("pimg"),islogin,isadmin,add)
route.get("/getprod",getprod)
route.put("/upddct",islogin,isadmin,upddct)
route.put("/deldct",islogin,isadmin,deldct)
route.put("/updprod",islogin,isadmin,updprod)
route.put("/updimg",upload.single("pimg"),islogin,isadmin,updpimg)
route.post("/addcart",islogin,addcart)
route.put("/inc",islogin,incqty)
route.put("/dec",islogin,decqty)
route.delete("/delcart/:id",islogin,delcart)
route.get("/getcart/:uid",islogin,getcart)
route.put("/addrv",islogin,addrv)
route.post("/restpwd",resetpwd)

route.delete("/deleteprod/:id",deleteProd)
module.exports=route
